import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import * as React from 'React'
import Home from '../components/home'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Layout() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
      <div className={styles.container}>
        <Navbar></Navbar>
        <Home></Home>
      </div>
      </main>
    </>
  )
}
